### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by amazurkiewicz-mobilereality** [nikolskiy/JavaScript-word-search#2]
I get this error, after about 1 minute of running the program: 
```
Adding words to the trie ...
Traceback (most recent call last):
  File "txt2trieDictConvert.py", line 166, in <module>
    main()
  File "txt2trieDictConvert.py", line 138, in main
    trie.addWord(line.strip('\n'))
  File "txt2trieDictConvert.py", line 101, in addWord
    item.mergeWith(branch.children[0])
IndexError: list index out of range
``` 

The dictionary file I use the script on is quite big, it has about 4M lines.

**Comment by nikolskiy** [comment]
Yeah, looks like you are running into memory limitation. In order to support unlimited dictionary sizes the project would need to save intermediate results into a file.
